{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.serviceName" . }}
  namespace: {{ include "mongodb.namespace" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- if .Values.internalAccess.enabled }}
  annotations:
    dns.pfsense.org/enabled: "true"
    dns.pfsense.org/hostname: {{ .Values.internalAccess.hostname | quote }}
  {{- end }}
spec:
  {{- if .Values.internalAccess.enabled }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.port }}
      targetPort: mongodb
      protocol: TCP
      name: mongodb
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
{{- end }}
