{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-server.serviceName" . }}
  namespace: {{ include "web-server.namespace" . }}
  labels:
    {{- include "web-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "web-server.selectorLabels" . | nindent 4 }}
{{- end }}
