{{- if .Values.vault.basePath }}
{{- if or .Values.postgres.enabled .Values.mongodb.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "rb-stack.dbSecretName" . }}
  namespace: {{ include "rb-stack.namespace" . }}
  labels:
    {{- include "rb-stack.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "rb-stack.secretStoreName" . }}
    kind: SecretStore
  target:
    name: {{ include "rb-stack.dbSecretName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.vault.basePath }}/{{ .Values.environment }}/db
  {{- if .Values.vault.remap.db }}
  {{- if gt (len .Values.vault.remap.db) 0 }}
  data:
    {{- range $vaultKey, $secretKey := .Values.vault.remap.db }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $.Values.vault.basePath }}/{{ $.Values.environment }}/db
        property: {{ $vaultKey }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
