{{- if .Values.vault.basePath }}
{{- if .Values.redis.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "rb-stack.redisSecretName" . }}
  namespace: {{ include "rb-stack.namespace" . }}
  labels:
    {{- include "rb-stack.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval | default "30s" }}
  secretStoreRef:
    name: {{ include "rb-stack.secretStoreName" . }}
    kind: SecretStore
  target:
    name: {{ include "rb-stack.redisSecretName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.vault.basePath }}/{{ .Values.environment }}/redis
  {{- if .Values.vault.remap.redis }}
  {{- if gt (len .Values.vault.remap.redis) 0 }}
  data:
    {{- range $vaultKey, $secretKey := .Values.vault.remap.redis }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $.Values.vault.basePath }}/{{ $.Values.environment }}/redis
        property: {{ $vaultKey }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
