{{- if .Values.vault.basePath }}
{{- if index .Values "web-server" "enabled" }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "rb-stack.appSecretName" . }}
  namespace: {{ include "rb-stack.namespace" . }}
  labels:
    {{- include "rb-stack.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "rb-stack.secretStoreName" . }}
    kind: SecretStore
  target:
    name: {{ include "rb-stack.appSecretName" . }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.vault.basePath }}/{{ .Values.environment }}/app
  {{- if .Values.vault.remap.app }}
  {{- if gt (len .Values.vault.remap.app) 0 }}
  data:
    {{- range $vaultKey, $secretKey := .Values.vault.remap.app }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $.Values.vault.basePath }}/{{ $.Values.environment }}/app
        property: {{ $vaultKey }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
