{{- if .Values.vault.basePath }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "rb-stack.secretStoreName" . }}
  namespace: {{ include "rb-stack.namespace" . }}
  labels:
    {{- include "rb-stack.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.mountPath }}
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: {{ include "rb-stack.vaultRole" . }}
          serviceAccountRef:
            name: {{ include "rb-stack.serviceAccountName" . }}
{{- end }}
