apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rb-stack.serviceAccountName" . }}
  namespace: {{ include "rb-stack.namespace" . }}
  labels:
    {{- include "rb-stack.labels" . | nindent 4 }}
